# Generated by Django 5.2.16 on 2026-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
