# Generated by Django 5.2.16 on 2026-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_threadparticipant_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
