# Generated by Django 5.2.16 on 2026-07-16 11:42

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10)),
                ('organization_type', models.CharField(blank=True, max_length=32)),
                ('is_global', models.BooleanField(default=False)),
                ('service_kinds', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('cities', models.JSONField(blank=True, default=list)),
                ('currencies', models.JSONField(blank=True, default=list)),
                ('communication_methods', models.JSONField(blank=True, default=list)),
                ('work_hours', models.CharField(blank=True, max_length=100)),
                ('settlement_type', models.CharField(blank=True, max_length=32)),
                ('contract_number', models.CharField(blank=True, max_length=64)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('automation_capabilities', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers_supplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('provider_adapter', models.CharField(max_length=100)),
                ('environment', models.CharField(default='sandbox', max_length=16)),
                ('encrypted_secrets', common.fields.EncryptedTextField(blank=True)),
                ('status', models.CharField(default='inactive', max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers_credential',
            },
        ),
        migrations.CreateModel(
            name='SupplierMarkupRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('service_kind', models.CharField(default='*', max_length=32)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('airline', models.CharField(blank=True, max_length=8)),
                ('cabin', models.CharField(blank=True, max_length=32)),
                ('passenger_category', models.CharField(blank=True, max_length=32)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=8)),
                ('amount_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('priority', models.IntegerField(default=100)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markup_rules', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers_markup_rule',
            },
        ),
        migrations.CreateModel(
            name='SupplierSearchPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('service_kind', models.CharField(max_length=32)),
                ('ordered_suppliers', models.JSONField(default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fallback_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers_search_priority',
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'status'], name='suppliers_s_tenant__bd9ec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('supplier', 'provider_adapter', 'environment'), name='uniq_supplier_credential'),
        ),
        migrations.AddIndex(
            model_name='suppliermarkuprule',
            index=models.Index(fields=['tenant', 'supplier', 'service_kind', 'priority'], name='suppliers_m_tenant__99e036_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliersearchpriority',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('archived_at__isnull', True)), fields=('tenant', 'service_kind'), name='uniq_active_search_priority'),
        ),
    ]
