# Generated by Django 5.2.16 on 2026-07-16 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('train_number', models.CharField(max_length=16)),
                ('train_type', models.CharField(blank=True, max_length=32)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('origin_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('departure_timezone', models.CharField(blank=True, max_length=63)),
                ('arrival_timezone', models.CharField(blank=True, max_length=63)),
                ('carriage_number', models.CharField(blank=True, max_length=8)),
                ('service_class', models.CharField(blank=True, max_length=16)),
                ('bedding_included', models.BooleanField(default=False)),
                ('meal_included', models.BooleanField(default=False)),
                ('refund_rules', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rail_segments', to='services.orderservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rail_segment',
            },
        ),
        migrations.CreateModel(
            name='RailSeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('seat_number', models.CharField(max_length=8)),
                ('seat_type', models.CharField(blank=True, max_length=16)),
                ('gender_requirement', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('held', 'Held'), ('booked', 'Booked'), ('released', 'Released'), ('expired', 'Expired')], default='held', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rail_seats', to='services.servicepassenger')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='rail.railsegment')),
            ],
            options={
                'db_table': 'rail_seat_hold',
            },
        ),
        migrations.AddConstraint(
            model_name='railsegment',
            constraint=models.UniqueConstraint(fields=('service', 'sequence'), name='uniq_rail_segment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='railseathold',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['held', 'booked'])), fields=('segment', 'seat_number'), name='uniq_active_rail_seat'),
        ),
    ]
