# Generated by Django 5.2.16 on 2026-07-16 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0002_initial'),
        ('suppliers', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleNumberCounter',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='tenancy.organization')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'aftersales_number_counter',
            },
        ),
        migrations.CreateModel(
            name='AfterSaleCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange'), ('cancellation', 'Cancellation'), ('certificate', 'Certificate')], max_length=14)),
                ('initiator', models.CharField(default='client', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('review', 'Review'), ('awaiting_client_approval', 'Awaiting Client Approval'), ('submitted_to_supplier', 'Submitted To Supplier'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='created', max_length=26)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('financial_snapshot', models.JSONField(blank=True, null=True)),
                ('external_references', models.JSONField(blank=True, default=dict)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_quote_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersale_cases', to='orders.order')),
                ('participants', models.ManyToManyField(blank=True, related_name='aftersale_cases', to='orders.orderparticipant')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aftersale_cases', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aftersale_cases', to='services.orderservice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aftersale_cases', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aftersales_case',
            },
        ),
        migrations.CreateModel(
            name='AfterSaleHistoryEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=48)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='aftersales.aftersalecase')),
            ],
            options={
                'db_table': 'aftersales_history',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AfterSaleQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('quote_version', models.PositiveIntegerField()),
                ('source', models.CharField(default='manual', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('original_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('agency_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_withholdings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('old_itinerary', models.JSONField(blank=True, null=True)),
                ('new_itinerary', models.JSONField(blank=True, null=True)),
                ('exchange_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='aftersales.aftersalecase')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aftersales_quote',
            },
        ),
        migrations.AddField(
            model_name='aftersalecase',
            name='current_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aftersales.aftersalequote'),
        ),
        migrations.AddConstraint(
            model_name='aftersalequote',
            constraint=models.UniqueConstraint(fields=('case', 'quote_version'), name='uniq_case_quote_version'),
        ),
        migrations.AddIndex(
            model_name='aftersalecase',
            index=models.Index(fields=['tenant', 'status', 'deadline'], name='aftersales__tenant__a62c14_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_aftersale_number'),
        ),
    ]
