# Generated by Django 5.2.16 on 2026-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviabooking',
            name='client_request_id',
            field=models.CharField(max_length=80),
        ),
    ]
