# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=32)),
                ('components', models.JSONField()),
                ('formula', models.TextField(blank=True)),
                ('rate_source', models.CharField(blank=True, max_length=64)),
                ('rate_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rounding', models.CharField(default='ROUND_HALF_UP', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services_price_snapshot',
            },
        ),
        migrations.CreateModel(
            name='SearchProviderRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('provider_adapter', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('offers_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'services_search_provider_run',
            },
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('avia', 'avia'), ('rail', 'rail'), ('hotel', 'hotel'), ('transfer', 'transfer'), ('bus', 'bus'), ('tour', 'tour'), ('aeroexpress', 'aeroexpress'), ('lounge', 'lounge'), ('insurance', 'insurance'), ('visa', 'visa'), ('other', 'other')], max_length=16)),
                ('criteria', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services_search_session',
            },
        ),
        migrations.CreateModel(
            name='ServiceExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('before_booking', 'Before Booking'), ('after_booking', 'After Booking'), ('after_issue', 'After Issue')], max_length=16)),
                ('availability', models.CharField(choices=[('provider', 'Provider'), ('manual', 'Manual'), ('unavailable', 'Unavailable')], default='manual', max_length=12)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(default='proposed', max_length=16)),
                ('emd_reference', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'services_service_extra',
            },
        ),
        migrations.CreateModel(
            name='ServiceExtraCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('avia', 'avia'), ('rail', 'rail'), ('hotel', 'hotel'), ('transfer', 'transfer'), ('bus', 'bus'), ('tour', 'tour'), ('aeroexpress', 'aeroexpress'), ('lounge', 'lounge'), ('insurance', 'insurance'), ('visa', 'visa'), ('other', 'other')], default='avia', max_length=16)),
                ('code', models.SlugField(max_length=63)),
                ('name', models.CharField(max_length=150)),
                ('stage', models.CharField(default='before_booking', max_length=16)),
                ('default_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'services_extra_catalog',
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('avia', 'avia'), ('rail', 'rail'), ('hotel', 'hotel'), ('transfer', 'transfer'), ('bus', 'bus'), ('tour', 'tour'), ('aeroexpress', 'aeroexpress'), ('lounge', 'lounge'), ('insurance', 'insurance'), ('visa', 'visa'), ('other', 'other')], max_length=16)),
                ('provider_adapter', models.CharField(blank=True, max_length=100)),
                ('external_key', models.CharField(blank=True, max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('itinerary', models.JSONField()),
                ('fare', models.JSONField(blank=True, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_currency', models.CharField(max_length=3)),
                ('availability', models.CharField(blank=True, max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_snapshot', models.JSONField(blank=True, null=True)),
                ('dedup_hash', models.CharField(blank=True, max_length=64)),
                ('exchange_rate_snapshot', models.JSONField(blank=True, null=True)),
                ('applied_markup_rules', models.JSONField(blank=True, null=True)),
                ('compliance', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services_service_offer',
            },
        ),
        migrations.CreateModel(
            name='ServicePassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('fare_code', models.CharField(blank=True, max_length=64)),
                ('room_ref', models.CharField(blank=True, max_length=64)),
                ('seat_ref', models.CharField(blank=True, max_length=16)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'services_service_passenger',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('avia', 'avia'), ('rail', 'rail'), ('hotel', 'hotel'), ('transfer', 'transfer'), ('bus', 'bus'), ('tour', 'tour'), ('aeroexpress', 'aeroexpress'), ('lounge', 'lounge'), ('insurance', 'insurance'), ('visa', 'visa'), ('other', 'other')], max_length=16)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('proposed', 'Proposed'), ('approval', 'Approval'), ('booked', 'Booked'), ('confirmed', 'Confirmed'), ('issued', 'Issued'), ('refund_in_progress', 'Refund In Progress'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='proposed', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(choices=[('api', 'Api'), ('manual', 'Manual'), ('import', 'Import')], default='api', max_length=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('supplier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('agency_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('client_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('ticketing_deadline', models.DateTimeField(blank=True, null=True)),
                ('provider_snapshot', models.JSONField(blank=True, null=True)),
                ('policy_compliance', models.JSONField(blank=True, null=True)),
                ('cancellation_rules', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='orders.order')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_order_service',
            },
        ),
    ]
