# Generated by Django 5.2.16 on 2026-07-16 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_initial'),
        ('orders', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.CharField(choices=[('classic_block', 'Classic Block'), ('split_individual', 'Split Individual')], default='classic_block', max_length=20)),
                ('airline', models.CharField(blank=True, max_length=3)),
                ('requested_seats', models.PositiveSmallIntegerField(default=0)),
                ('confirmed_seats', models.PositiveSmallIntegerField(default=0)),
                ('deposit_deadline', models.DateTimeField(blank=True, null=True)),
                ('names_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('request_sent', 'Request Sent'), ('quoted', 'Quoted'), ('deposit_pending', 'Deposit Pending'), ('confirmed', 'Confirmed'), ('names_pending', 'Names Pending'), ('names_submitted', 'Names Submitted'), ('partially_ticketed', 'Partially Ticketed'), ('ticketed', 'Ticketed'), ('reduced', 'Reduced'), ('cancelled', 'Cancelled')], default='preparing', max_length=20)),
                ('split_state', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='group_order', to='orders.order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_orders', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_group_order',
            },
        ),
        migrations.CreateModel(
            name='GroupBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('seats', models.PositiveSmallIntegerField()),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fare_currency', models.CharField(blank=True, max_length=3)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='groups_app.grouporder')),
            ],
            options={
                'db_table': 'groups_block',
            },
        ),
        migrations.CreateModel(
            name='GroupPassengerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=8)),
                ('baggage', models.CharField(blank=True, max_length=32)),
                ('fare_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='assigned', max_length=16)),
                ('ticket_number', models.CharField(blank=True, max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups_app.groupblock')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='orders.orderparticipant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_passenger_assignment',
            },
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='groups_app.grouporder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_request',
            },
        ),
        migrations.CreateModel(
            name='GroupSupplierResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('quoted_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='groups_app.grouprequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_supplier_response',
            },
        ),
        migrations.CreateModel(
            name='PassengerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(default='tourist', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_groups', to='crm.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_passenger_group',
            },
        ),
        migrations.CreateModel(
            name='GroupSubgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='groups_app.passengergroup')),
            ],
            options={
                'db_table': 'groups_subgroup',
            },
        ),
        migrations.AddField(
            model_name='grouporder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_orders', to='groups_app.passengergroup'),
        ),
        migrations.CreateModel(
            name='RosterImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('raw_rows', models.JSONField(blank=True, default=list)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('decisions', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('preview_ready', 'Preview Ready'), ('applied', 'Applied'), ('failed', 'Failed')], default='uploaded', max_length=14)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_imports', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_roster_import',
            },
        ),
        migrations.CreateModel(
            name='RosterMergeHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField()),
                ('decision', models.CharField(max_length=16)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_history', to='groups_app.rosterimportjob')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.person')),
            ],
            options={
                'db_table': 'groups_roster_merge_history',
            },
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.UniqueConstraint(fields=('group_order', 'name'), name='uniq_block_name'),
        ),
        migrations.AddConstraint(
            model_name='grouppassengerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['replaced', 'removed']), _negated=True), fields=('block', 'participant'), name='uniq_block_participant'),
        ),
        migrations.AddConstraint(
            model_name='groupsubgroup',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_subgroup_name'),
        ),
    ]
