# Generated by Django 5.2.16 on 2026-09-08 10:26

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengergroup',
            name='roster',
            field=common.fields.EncryptedTextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='passengergroup',
            name='roster_subgroups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
