# Generated by Django 5.2.16 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sync_receipt_editor_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
