# Generated by Django 5.2.16 on 2026-07-16 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preflight_ok', 'Preflight Ok'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=14)),
                ('plan_snapshot', models.JSONField(blank=True, null=True)),
                ('preflight_result', models.JSONField(blank=True, null=True)),
                ('preflight_at', models.DateTimeField(blank=True, null=True)),
                ('price_confirmation_required', models.BooleanField(default=False)),
                ('prices_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.backgroundjob')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_workflows', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_workflow',
            },
        ),
        migrations.CreateModel(
            name='BookingWorkflowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booking', 'Booking'), ('booked', 'Booked'), ('issuing', 'Issuing'), ('issued', 'Issued'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('compensated', 'Compensated'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('locator', models.CharField(blank=True, max_length=32)),
                ('provider_result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_items', to='services.orderservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.bookingworkflow')),
            ],
            options={
                'db_table': 'booking_workflow_item',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingworkflow',
            index=models.Index(fields=['tenant', 'order', 'status'], name='booking_wor_tenant__19dee9_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingworkflowitem',
            constraint=models.UniqueConstraint(fields=('workflow', 'service'), name='uniq_workflow_service'),
        ),
    ]
