# Generated by Django 5.2.16 on 2026-07-16 11:59

import django.db.models.deletion
import offers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalNumberCounter',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='tenancy.organization')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'offers_proposal_counter',
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=63)),
                ('name', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers_proposal_template',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('sent', 'Sent'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.proposaltemplate')),
            ],
            options={
                'db_table': 'offers_proposal',
            },
        ),
        migrations.CreateModel(
            name='ProposalVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='proposed', max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='offers.proposal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers_proposal_variant',
            },
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_currency', models.CharField(max_length=3)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_items', to='services.serviceoffer')),
                ('price_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.pricesnapshot')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_items', to='services.orderservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.proposalvariant')),
            ],
            options={
                'db_table': 'offers_proposal_item',
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='approved_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.proposalvariant'),
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('template_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='offers.proposal')),
            ],
            options={
                'db_table': 'offers_proposal_version',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=16)),
                ('scenario', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('chosen', 'Chosen'), ('declined', 'Declined'), ('expired', 'Expired'), ('price_changed', 'Price Changed'), ('unavailable', 'Unavailable'), ('issued', 'Issued')], default='created', max_length=14)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('card_version', models.PositiveIntegerField(default=1)),
                ('public_token', models.CharField(default=offers.models._card_token, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_cards', to='services.serviceoffer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_cards', to='orders.order')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_cards', to='services.orderservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers_service_card',
            },
        ),
        migrations.CreateModel(
            name='ServiceCardDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(max_length=16)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('external_message_id', models.CharField(blank=True, max_length=128)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='offers.servicecard')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers_card_delivery',
            },
        ),
        migrations.CreateModel(
            name='ServiceCardResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=16)),
                ('external_identity', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='offers.servicecard')),
            ],
            options={
                'db_table': 'offers_card_response',
            },
        ),
        migrations.AddConstraint(
            model_name='proposaltemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'code', 'template_version'), name='uniq_proposal_template_version'),
        ),
        migrations.AddConstraint(
            model_name='proposalvariant',
            constraint=models.UniqueConstraint(fields=('proposal', 'sequence'), name='uniq_variant_sequence'),
        ),
        migrations.AddConstraint(
            model_name='proposalvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('proposal',), name='uniq_approved_variant'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['tenant', 'order', 'status'], name='offers_prop_tenant__332f29_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_proposal_number'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='uniq_proposal_version'),
        ),
        migrations.AddIndex(
            model_name='servicecard',
            index=models.Index(fields=['tenant', 'order', 'status'], name='offers_serv_tenant__bc3db7_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecardresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('action__in', ['choose', 'decline'])), fields=('card', 'card_version'), name='uniq_terminal_card_response'),
        ),
    ]
