# Generated by Django 5.2.16 on 2026-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalitem',
            name='service_kind',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
