# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCorrectionPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('document_kind', models.CharField(blank=True, max_length=24)),
                ('field', models.CharField(max_length=100)),
                ('preferred_wording', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'documents_correction_preference',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=63)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('itinerary_receipt', 'Itinerary Receipt'), ('ticket', 'Ticket'), ('voucher', 'Voucher'), ('insurance_policy', 'Insurance Policy'), ('invoice', 'Invoice'), ('act', 'Act'), ('contract', 'Contract'), ('passport', 'Passport'), ('application', 'Application'), ('supplier_confirmation', 'Supplier Confirmation'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=24)),
                ('body', models.TextField()),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents_template',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=documents.models._version_upload_path)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(default='uploaded', max_length=12)),
                ('template_version', models.CharField(blank=True, max_length=64)),
                ('scan_status', models.CharField(default='pending', max_length=12)),
                ('correction_reason', models.TextField(blank=True)),
                ('correction_diff', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents_document_version',
            },
        ),
        migrations.CreateModel(
            name='ReceiptDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('entity', models.CharField(blank=True, max_length=255)),
                ('trip_type', models.CharField(blank=True, max_length=16)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents_receipt_draft',
            },
        ),
        migrations.CreateModel(
            name='ReceiptImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('guessed_type', models.CharField(blank=True, max_length=24)),
                ('parser_status', models.CharField(default='pending', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('raw_extraction', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'documents_receipt_import',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('itinerary_receipt', 'Itinerary Receipt'), ('ticket', 'Ticket'), ('voucher', 'Voucher'), ('insurance_policy', 'Insurance Policy'), ('invoice', 'Invoice'), ('act', 'Act'), ('contract', 'Contract'), ('passport', 'Passport'), ('application', 'Application'), ('supplier_confirmation', 'Supplier Confirmation'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('accounting', 'Accounting'), ('signing', 'Signing'), ('signed', 'Signed'), ('void', 'Void')], default='draft', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(default='upload', max_length=16)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('requires_signing', models.BooleanField(default=False)),
                ('is_confidential', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='crm.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
            },
        ),
    ]
