# Generated by Django 5.2.16 on 2026-07-16 12:15

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models._version_upload_path),
        ),
    ]
