# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('documents', '0003_initial'),
        ('tenancy', '0001_initial'),
        ('travel_policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='travel_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='travel_policy.travelpolicy'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crm.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerule',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='crm.agreement'),
        ),
        migrations.AddField(
            model_name='feerule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='feerule',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crm.feetemplate'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='fee_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.feetemplate'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='crm.person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='crm.person'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_contacts', to='crm.person'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='crm.person'),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.person'),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='crm.company'),
        ),
        migrations.AddField(
            model_name='settlementprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='settlementprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant', 'status'], name='crm_company_tenant__dedfa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('tax_id', ''), _negated=True)), fields=('tenant', 'tax_id'), name='uniq_company_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('tenant', 'company', 'number'), name='uniq_contract_number'),
        ),
        migrations.AddConstraint(
            model_name='feerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation', 'fixed'), _negated=True), models.Q(('currency', ''), _negated=True), _connector='OR'), name='check_fixed_fee_has_currency'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(fields=('contract', 'agreement_version'), name='uniq_agreement_version'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tenant', 'surname', 'given_name'], name='crm_person_tenant__ab382d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tenant', 'phone'], name='crm_person_tenant__4ace5a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tenant', 'email'], name='crm_person_tenant__d7d987_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tenant', 'birth_date'], name='crm_person_tenant__f6e7ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycard',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'number'), name='uniq_loyalty_card'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('company', 'person'), name='uniq_company_employee'),
        ),
        migrations.AddConstraint(
            model_name='companycontact',
            constraint=models.UniqueConstraint(fields=('company', 'person'), name='uniq_company_contact'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['tenant', 'status'], name='crm_client__tenant__8f769a_idx'),
        ),
        migrations.AddConstraint(
            model_name='persondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('tenant', 'type', 'issuing_country', 'number_hash'), name='uniq_person_document_number'),
        ),
        migrations.AddConstraint(
            model_name='settlementprofile',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_reserved__lte', models.F('deposit_balance')), ('mode__in', ['prepayment', 'credit']), _connector='OR'), name='check_deposit_reserve'),
        ),
    ]
