# Generated by Django 5.2.16 on 2026-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latin_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
