# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationErrorCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=32)),
                ('default_severity', models.CharField(default='medium', max_length=10)),
                ('recommended_action', models.TextField(blank=True)),
                ('is_retry_safe', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'integrations_error_code',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('provider_adapter', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('request_sanitized', models.JSONField(blank=True, null=True)),
                ('response_sanitized', models.JSONField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('raw_error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integrations_log',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimelineEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_incident_timeline',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationIncident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=100)),
                ('severity', models.CharField(default='medium', max_length=10)),
                ('provider_adapter', models.CharField(blank=True, max_length=100)),
                ('operation', models.CharField(blank=True, max_length=100)),
                ('sanitized_error', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('snoozed', 'Snoozed'), ('retrying', 'Retrying'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('escalated', 'Escalated')], default='open', max_length=10)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('resolution_code', models.CharField(blank=True, max_length=100)),
                ('resolution_comment', models.TextField(blank=True)),
                ('developer_ticket', models.CharField(blank=True, max_length=255)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_incident',
            },
        ),
    ]
