# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('integrations', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationincident',
            name='fallback_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='integrationincident',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='common.backgroundjob'),
        ),
        migrations.AddField(
            model_name='integrationincident',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='orders.order'),
        ),
        migrations.AddField(
            model_name='integrationincident',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='services.orderservice'),
        ),
        migrations.AddField(
            model_name='integrationincident',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='integrationincident',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='incidenttimelineentry',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='integrations.integrationincident'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='integrationincident',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='integration_tenant__3caad4_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationincident',
            index=models.Index(fields=['tenant', 'error_code'], name='integration_tenant__93115f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['tenant', 'correlation_id'], name='integration_tenant__ec3108_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['tenant', 'provider_adapter', '-created_at'], name='integration_tenant__70d769_idx'),
        ),
    ]
