# Generated by Django 5.2.16 on 2026-07-16 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='tenancy.organization')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'orders_number_counter',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('request_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('corporate', 'Corporate')], default='individual', max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('data_missing', 'Data Missing')], default='new', max_length=24)),
                ('stage', models.CharField(choices=[('created', 'Created'), ('service_selection', 'Service Selection'), ('booking', 'Booking'), ('ticketing', 'Ticketing'), ('documents', 'Documents'), ('completed', 'Completed')], default='created', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('preferred_channel', models.CharField(blank=True, max_length=32)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('agreement_snapshot', models.JSONField(blank=True, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('is_group', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.agreement')),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.company')),
                ('client_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.person')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.person')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.CreateModel(
            name='OrderParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('guest_snapshot', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(choices=[('passenger', 'Passenger'), ('contact', 'Contact'), ('approver', 'Approver'), ('other', 'Other')], default='passenger', max_length=10)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('subgroup_name', models.CharField(blank=True, max_length=100)),
                ('is_contact', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('booking_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.persondocument')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='orders.order')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='crm.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_participant',
            },
        ),
        migrations.CreateModel(
            name='OrderReassignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('new_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='orders.order')),
                ('previous_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_reassignment',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'orders_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=8)),
                ('status', models.CharField(default='open', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_task',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], default='one_way', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_route',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('location_code', models.CharField(max_length=8)),
                ('location_type', models.CharField(default='city', max_length=16)),
                ('location_name', models.CharField(blank=True, max_length=150)),
                ('local_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=63)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='orders.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_route_point',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='orders_orde_tenant__291115_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'operator', 'status'], name='orders_orde_tenant__992ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', '-created_at'], name='orders_orde_tenant__b7367d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'planned_start'], name='orders_orde_tenant__8dd65b_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_order_number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_company__isnull', True), ('client_person__isnull', False)), models.Q(('client_company__isnull', False), ('client_person__isnull', True)), _connector='OR'), name='check_order_client_xor'),
        ),
        migrations.AddConstraint(
            model_name='orderparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('person__isnull', False)), fields=('order', 'person'), name='uniq_active_participant'),
        ),
        migrations.AddConstraint(
            model_name='orderparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('guest_snapshot__isnull', False), _connector='OR'), name='check_participant_person_or_guest'),
        ),
        migrations.AddIndex(
            model_name='ordertask',
            index=models.Index(fields=['tenant', 'assignee', 'status'], name='orders_task_tenant__01c261_idx'),
        ),
        migrations.AddConstraint(
            model_name='routepoint',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_route_point_sequence'),
        ),
    ]
