# Generated by Django 5.2.16 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
